# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 16:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanceOnTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_name', models.CharField(max_length=64)),
                ('time_signature', models.CharField(max_length=5)),
                ('tempo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(50)])),
                ('ticks_mp3', models.CharField(max_length=128)),
                ('vocals_mp3', models.CharField(max_length=128)),
            ],
        ),
    ]
