# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_dance_role', models.CharField(choices=[('lead', 'LEAD'), ('follow', 'FOLLOW'), ('both', 'BOTH')], default='lead', max_length=6)),
                ('competitive_level', models.CharField(choices=[('social only', 'SOCIAL'), ('newcomer', 'NEWCOMER'), ('novice', 'NOVICE'), ('intermediate', 'INTERMEDIATE'), ('advanced', 'ADVANCED'), ('allstar', 'ALLSTAR')], default='social only', max_length=12)),
                ('years_dancing', models.IntegerField(choices=[('MONTHS', '< 1'), ('ONE', '1'), ('TWO', '2'), ('THREE', '3'), ('FOUR', '4'), ('FIVE', '5'), ('SIX', '6'), ('SEVEN', '7'), ('EIGHT', '8'), ('NINE', '9'), ('TEN', '10+')], default=0)),
                ('age', models.IntegerField()),
                ('dj', models.BooleanField()),
                ('other_dances', models.BooleanField()),
                ('region', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='OtherDances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('other', models.TextField()),
                ('dancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatiswcs.Dancer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('features', models.TextField()),
                ('groove_url', models.TextField()),
            ],
        ),
    ]
