# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancer',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
