# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0002_auto_20170927_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='competitive_level',
            field=models.CharField(choices=[('SOCIAL', 'Social Only'), ('NEWCOMER', 'Newcomer'), ('NOVICE', 'Novice'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('ALLSTAR', 'All-Star')], default='SOCIAL', max_length=12),
        ),
    ]
