# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0004_auto_20170924_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherDances',
            new_name='OtherDance',
        ),
    ]
