# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0004_songanddancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songanddancer',
            name='other_dances',
        ),
    ]
