# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0005_remove_songanddancer_other_dances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songanddancer',
            name='song_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
