# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 05:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0005_auto_20170924_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdance',
            name='other',
        ),
    ]
