# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0006_remove_otherdance_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdance',
            name='dancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whatiswcs.Dancer'),
        ),
    ]
