# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0006_auto_20170927_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songanddancer',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='songanddancer',
            name='song_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
