# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:06
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0007_auto_20170928_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songanddancer',
            name='region',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
