# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0008_song_dancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancer',
            name='age',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='dancer',
            name='years_dancing',
            field=models.IntegerField(choices=[(0, '< 1'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10+')], default=0),
        ),
    ]
