# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0008_auto_20170928_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancer',
            name='song',
        ),
        migrations.DeleteModel(
            name='Dancer',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
