# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 04:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0009_auto_20170928_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songanddancer',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=6, null=True, validators=[django.core.validators.MinValueValidator(6)]),
        ),
    ]
