# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0009_auto_20170924_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='groove_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
