# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_countries.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0010_auto_20170928_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songanddancer',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True, validators=[django.core.validators.MinValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='songanddancer',
            name='other_dance_styles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('SMOOTH_BALLROOM', 'Smooth Ballroom Dances'), ('RHYTHM_BALLROOM', 'Rhythm/Latin Dances'), ('COUNTRY', 'Country Dances'), ('BLUES', 'Blues'), ('CLUB', 'Club Dances'), ('OTHER', 'Other Styles')], max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='songanddancer',
            name='primary_dance_role',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('FOLLOW', 'Follow'), ('BOTH', 'Both')], default='LEAD', max_length=6),
        ),
        migrations.AlterField(
            model_name='songanddancer',
            name='region',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
