# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0010_auto_20170924_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='dancer',
        ),
        migrations.AddField(
            model_name='dancer',
            name='song',
            field=models.ManyToManyField(blank=True, null=True, to='whatiswcs.Song'),
        ),
    ]
