# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 18:08
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0011_auto_20171002_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songanddancer',
            name='region',
            field=django_countries.fields.CountryField(default={'country': 'US'}, max_length=2),
        ),
    ]
