# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0011_auto_20170924_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdance',
            name='dancer',
        ),
        migrations.AddField(
            model_name='dancer',
            name='other_dance_styles',
            field=models.ManyToManyField(blank=True, null=True, to='whatiswcs.OtherDance'),
        ),
    ]
