# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0012_auto_20171002_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songanddancer',
            name='song_url',
            field=models.URLField(default='https://www.youtube.com', verbose_name='Song URL'),
            preserve_default=False,
        ),
    ]
