# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatiswcs', '0014_auto_20170924_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dancer',
            name='song',
        ),
        migrations.AddField(
            model_name='songlist',
            name='dancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatiswcs.Dancer'),
        ),
        migrations.AddField(
            model_name='songlist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatiswcs.Song'),
        ),
        migrations.AddField(
            model_name='dancer',
            name='song',
            field=models.ManyToManyField(blank=True, null=True, through='whatiswcs.SongList', to='whatiswcs.Song'),
        ),
    ]
